### ISSUE TITLE
why can run.sh create datasets files?

### ISSUE THREAD

**Issue by S200331082** [sarahESL/PubMedCLIP#6]
hi there,  I used to train the MEVF in my local machine, as MEVF's `README.md` wrote: 

> All data should be downloaded via [link](https://vision.aioz.io/f/777a3737ee904924bf0d/?dl=1). The downloaded file should be extracted to data_RAD/ directory.

so I really want to know in your repository how the  `run.sh`  can create datasets files or some dictionaries files(I thought it should have a url at least?), I think this ought to be a low-level question(:
appreciated for your answer.

**Comment by sarahESL** [comment]
The datasets used in our work are well-known medvqa benchmarks and referenced in our preprint. You can refer to the original papers, i.e. SLAKE and VQA_RAD, and see how you can access + download them. 

Since these are medical data and usually considered to include "sensitive" data, I prefer that the audience themselves go through the data access process to get permissions for accessing the datasets rather than linking them directly or making them downloadable via my own repository. Once you downloaded the data, set the correct paths in the `run.sh` script to where you stored the datasets and run the script.

Nevertheless, if you need help finding the original urls for getting access to the datasets, let me know! :)

**Comment by S200331082** [comment]
> Nevertheless, if you need help finding the original urls for getting access to the datasets, let me know! :)

so sweet you are, SLAKE please, thanks! :)

**Comment by sarahESL** [comment]
For downloading SLAKE, please refer to [https://www.med-vqa.com/slake/](https://www.med-vqa.com/slake/ ). There is a section "Download" with the links to download the data.

**Comment by S200331082** [comment]
Thanks again
